language: node_js
node_js:
  - "6"
  - "4"

install:
  - npm install -g coveralls
  - npm prune
  - npm install

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true # ignore coveralls error
  - npm run filesize

# Allow Travis tests to run in containers.
sudo: false
