language: node_js
node_js:
  - "5.1"
  - "4.2"
install:
  - npm install -g coveralls
  - npm install

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info

# Allow Travis tests to run in containers.
sudo: false
