github_repo: apollographql/apollo-client
title: Apollo Client
propertytitle: Using GraphQL with Apollo Client
subtitle: React Guide
description: A guide to using the Apollo GraphQL Client with React.
versions:
  - '1'

content_root: docs/source
public_dir: public/docs/react

url: https://www.apollographql.com/docs/react
root: /docs/react/

typescript_api_box:
  data_file: docs.json

# This setting also defines the page order used to generate the
# Previous/Next links at the bottom of each page
sidebar_categories:
  # Basics
  null:
    - index
    - why-apollo
    - integrations
    - react-apollo-migration
  Essentials:
    - essentials/get-started
    - essentials/queries
    - essentials/mutations
    - essentials/local-state
  Features:
    - features/error-handling
    - features/pagination
    - features/optimistic-ui
    - features/server-side-rendering
    - features/performance
    - features/developer-tooling
  Advanced:
    - advanced/boost-migration
    - advanced/subscriptions
    - advanced/network-layer
    - advanced/caching
    - advanced/fragments
  Recipes:
    - recipes/authentication
    - recipes/2.0-migration
    - recipes/static-typing
    - recipes/react-native
    - recipes/babel
    - recipes/webpack
    - recipes/meteor
    - recipes/recompose
  API:
    - api/apollo-client
    - api/react-apollo

redirects:
  /docs/react/essentials/get-started.html#api:
    docs/react/api/react-apollo.html
  /docs/react/essentials/queries.html#api:
    docs/react/api/react-apollo.html#graphql-query-options
  /docs/react/basics/mutations.html#api:
    docs/react/api/react-apollo.html#graphql-mutation-options
