# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Apollo JavaScript Core
subtitle: Core API Documentation for the Apollo JS GraphQL Client
description:
author:
language:
timezone:
versions:
  - '1'

# This setting also defines the page order used to generate the Previous/Next links at the bottom of each page
sidebar_categories:
  null:
    - index
    - apollo-client-api
  'Technical Documentation':
    - network
    - fragments
    - devtools
    - how-it-works
  Integrations:
    - meteor

# not sure if we should rename this?
github_repo: apollostack/docs
content_root: source

logo:
  nav_mobile: logo/logo-apollo-space.svg
  title: Apollo Developers
  subtitle: Developers
  url: http://dev.apollodata.com/
  target: _new
favicon: logo/favicon.png

typescript_api_box:
  data_file: docs.json

nav_links:
  'Angular 2':
    url: http://dev.apollodata.com/angular2
  'React':
    url: http://dev.apollodata.com/react
  'Core JS':
    url: http://dev.apollodata.com/core
    active: true
  'Server':
    url: http://dev.apollodata.com/tools
  # 'Community':
  #   url: http://dev.apollodata.com/community
  'Blog':
    url: https://medium.com/apollo-stack
    target: _new

social_links:
  github: 'https://github.com/apollostack'
  twitter: '@apollostack'

# API keys
apis:
  segment: wgrIo8Bul0Ujl8USETG3DB6hONdy4kTg

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://dev.apollodata.com/core
root: /core/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: meteor

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type:
